// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotED0ykHUftNxihb7bxGqQdlTArn9BIw',
    appId: '1:636762004341:web:082ee06eb27e137b5e913c',
    messagingSenderId: '636762004341',
    projectId: 'rongila-reshom',
    authDomain: 'rongila-reshom.firebaseapp.com',
    storageBucket: 'rongila-reshom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAanhQwaNSPPse1yO4hLB8PuKfjF6jqwZ0',
    appId: '1:636762004341:android:80772c0458c047295e913c',
    messagingSenderId: '636762004341',
    projectId: 'rongila-reshom',
    storageBucket: 'rongila-reshom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpGmRWRytHjK7eOOuLTgKNuG8v75z9n8',
    appId: '1:636762004341:ios:564d43d8ce5c62c35e913c',
    messagingSenderId: '636762004341',
    projectId: 'rongila-reshom',
    storageBucket: 'rongila-reshom.firebasestorage.app',
    iosBundleId: 'com.example.rongilareshom',
  );
}
